version: "3"
services:
  bytebank:
    build: ./bytebank-app
    container_name: bytebank
    ports:
      - "3000:80"

  login:
    build: ./teck-bank-mfe-architecture
    container_name: login
    ports:
      - "3001:80"

  nginx:
    image: nginx:alpine
    container_name: gateway
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - bytebank
      - login
